server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: http://localhost:3001/
          predicates:
            - Path=/**
          filters:
            - RewritePath=/?(?<segment>.*), /$\{segment}