server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: http://localhost:4000/
          predicates:
            - Path=/message/**
          filters:
            - RewritePath=//?(?<segment>.*), /v1.0/invoke/message/method/$\{segment}
        - id: event-service
          uri: http://localhost:4000/
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=//?(?<segment>.*), /v1.0/invoke/event-service/method/$\{segment}